 SET TALK OFF
 PUBLIC swTrue, swFalse, swSecond
 swTrue = .T.
 swFalse = .F.
 swSecond = 18
 PUBLIC coM1, coM2, coM3, coM4, coM5, coM6, coM7, coM8
 PUBLIC coM9, coM10, coM11, coM12, coM13, coM14, coM15, coM16
 PUBLIC coM17, coM18, coM19, coM20, coM21, coM22, coM23, coM24
 PUBLIC coM25, coM26, coM27, coM28, coM29, coM30, coM31, coM32
 PUBLIC coM33, coM34
 coM1 = 0
 coM2 = 1
 coM3 = 2
 coM4 = 3
 coM5 = 4
 coM6 = 5
 coM7 = 6
 coM8 = 7
 coM9 = 8
 coM10 = 9
 coM11 = 10
 coM12 = 11
 coM13 = 12
 coM14 = 13
 coM15 = 14
 coM16 = 15
 coM17 = 16
 coM18 = 17
 coM19 = 18
 coM20 = 19
 coM21 = 20
 coM22 = 21
 coM23 = 22
 coM24 = 23
 coM25 = 24
 coM26 = 25
 coM27 = 26
 coM28 = 27
 coM29 = 28
 coM30 = 29
 coM31 = 30
 coM32 = 31
 coM33 = 32
 coM34 = 33
 PUBLIC irQ2, irQ3, irQ4, irQ5, irQ6, irQ7
 irQ2 = 2
 irQ3 = 3
 irQ4 = 4
 irQ5 = 5
 irQ6 = 6
 irQ7 = 7
 PUBLIC irQ8, irQ9, irQ10, irQ11, irQ12, irQ13, irQ14, irQ15
 PUBLIC coM1baseio, coM2baseio
 irQ8 = 8
 irQ9 = 9
 irQ10 = 10
 irQ11 = 11
 irQ12 = 12
 irQ13 = 13
 irQ14 = 14
 irQ15 = 15
 coM1baseio = 1016
 coM2baseio = 760
 PUBLIC coM3baseio, coM4baseio, coM5baseio, coM6baseio, coM7baseio, coM8baseio
 coM3baseio = 12832
 coM4baseio = 12840
 coM5baseio = 16928
 coM6baseio = 16936
 coM7baseio = 21024
 coM8baseio = 21032
 PUBLIC swNoasdtr, swNoasrts, swCuseint1
 swNoasdtr = 1
 swNoasrts = 2
 swCuseint1 = 4
 swNouartfi = 8
 swEnableua = 16
 PUBLIC swAsdtr, swAsrts, swDeasdtr, swDeasrts, swNofree, swNorestor
 swAsdtr = 1
 swAsrts = 2
 swDeasdtr = 4
 swDeasrts = 8
 swNofree = 16
 swNorestor = 32
 PUBLIC swCsuccess, swCinvalid, swCqueueis, swCqueueis
 PUBLIC swCinvalid, swCnouartp, swCnointav, swCnointsp
 PUBLIC swCnomemor, swCtimedou, swCabort, swCnotfoun, swCnocarri
 PUBLIC swCunablet, swCbadbloc, swCnoremot
 PUBLIC swClocalab, swCremotea, swCbadbloc, swCblockfr
 PUBLIC swCreceive, swCeotdete, swCmaxleng
 PUBLIC swCtermina, swCqueuewe, swCfeature
 PUBLIC swCfilewri, swCfileclo, swCfileexi, swCfilesee
 PUBLIC swCzmexnew, swCzmdatel, swCzmnewfi, swCzmfiles
 PUBLIC swCzmbadhe, swCzmbades, swCzmgarbl
 swCsuccess = 0
 swCinvalid = -500
 swCqueueis = -499
 swCqueueis = -498
 swCinvalid = -497
 swCnouartp = -496
 swCnointav = -495
 swCnointsp = -494
 swCnomemor = -493
 swCtimedou = -492
 swCabort = -491
 swCnotfoun = -490
 swCnocarri = -489
 swCunablet = -488
 swCbadbloc = -487
 swCnoremot = -486
 swClocalab = -485
 swCremotea = -484
 swCbadbloc = -483
 swCblockfr = -482
 swCreceive = -481
 swCeotdete = -480
 swCmaxleng = -479
 swCtermina = -478
 swCqueuewe = -477
 swCfeature = -476
 swCfilewri = -475
 swCfileclo = -474
 swCfileexi = -473
 swCfilesee = -472
 swCzmexnew = -471
 swCzmdatel = -470
 swCzmnewfi = -469
 swCzmfiles = -468
 swCzmbadhe = -467
 swCzmbades = -466
 swCzmgarbl = -465
 PUBLIC swParityno, swParityod, swParityev, swParityst, swParityms
 PUBLIC swParityma, swParitysp
 swParityno = 0
 swParityod = 8
 swParityev = 24
 swParityst = 40
 swParityms = 56
 swParityma = 40
 swParitysp = 56
 PUBLIC txWforxon, txWforcts, txWfordsr, txWforcarr, txWformanu
 txWforxon = 1
 txWforcts = 2
 txWfordsr = 4
 txWforcarr = 8
 txWformanu = 16
 PUBLIC xoNxoffise, rtSctsisen, dtRdsrisen, caRrdetise
 xoNxoffise = 1
 rtSctsisen = 2
 dtRdsrisen = 4
 caRrdetise = 8
 PUBLIC swCsmoff, swCsmon, swCsmmodep, swCsmmodet
 swCsmoff = '0'
 swCsmon = '1'
 swCsmmodep = 0
 swCsmmodet = 1
 PUBLIC swBlack, swBlue, swGreen, swCyan, swRed, swMagenta, swBrown
 PUBLIC swWhite, swBlink, swIntense
 swBlack = 0
 swBlue = 1
 swGreen = 2
 swCyan = 3
 swRed = 4
 swMagenta = 5
 swBrown = 6
 swWhite = 7
 swBlink = 128
 swIntense = 8
 PUBLIC swPosreg0, swPosreg1, swPosreg2, swPosreg3, swPosreg4
 PUBLIC swPosreg5, swPosreg6, swPosreg7, swPosminch, swPosmaxch
 swPosreg0 = 0
 swPosreg1 = 1
 swPosreg2 = 2
 swPosreg3 = 3
 swPosreg4 = 4
 swPosreg5 = 5
 swPosreg6 = 6
 swPosreg7 = 7
 swPosminch = 0
 swPosmaxch = 7
 PUBLIC swPosibmdu
 swPosibmdu = 61183
 PUBLIC swPos16dig, swPos8digi, swPos4digi
 swPos16dig = 28644
 swPos8digi = 28645
 swPos4digi = 28646
 RETURN
*
